Get all cities and weather for one city
fedebrasburg/tp0-taller pull request #1
Opened 2017-08-18 01:43 UTC by fedebrasburg

2017-08-18 21:24 UTC, pciruzzi commented on weather/services/files/cityList.json
> +[
Esto lo hiciste por el tema de los 27MB?

2017-08-18 21:42 UTC, fedebrasburg commented on weather/services/files/cityList.json
> +[
Si, provisorio hasta que tomemos una decisión

2017-08-23 21:23 UTC, pciruzzi requested changes
Habría que hacer algunos tests, más allá de eso lo veo bien! Si querés lo podemos dejar para otro PR así cerramos esto

2017-08-23 21:33 UTC, pciruzzi approved these changes

2017-08-23 21:34 UTC, merged