Use babel to use es6 completely
fedebrasburg/tp0-taller pull request #6
Opened 2017-08-25 23:08 UTC by pciruzzi

Closes #4

2017-08-26 02:54 UTC, fedebrasburg requested changes
Fix Travis

2017-08-26 02:54 UTC, fedebrasburg commented on dist/services/weatherService.js
> +var _bluebird2 = _interopRequireDefault(_bluebird);
??

2017-08-26 17:33 UTC, pciruzzi commented
♻️ @fedebrasburg

2017-08-27 04:38 UTC, fedebrasburg approved these changes

2017-08-27 04:38 UTC, fedebrasburg commented
Estas mergeando a master?

2017-08-27 04:47 UTC, pciruzzi commented
Parece que si, me parece que debe ser un tema de configuración de github, porque esta vez estoy seguro que salí de develop jajaj

2017-08-27 15:13 UTC, merged